services:
  - type: web
    name: bolsalaboral-back
    runtime: docker
    plan: free
    envVars:
      - key: DB_HOST
        value: aws-1-us-west-2.pooler.supabase.com
      - key: DB_PORT
        value: "6543"
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres.wpcquwfejnfxpobzquwg
      - key: DB_PASS
        value: BSIxW4Tpe3yaewws
      - key: API_KEY
        value: bolsalaboral-hackathon-2026
      - key: FRONTEND_URL
        value: https://phyton06.github.io/BolsaLaboralFront
      - key: APP_URL
        value: https://bolsalaboralback.onrender.com
